"use client";
import { useEffect, useState } from "react";
import { searchTickers } from "../../lib/api";
import { INTENTS, STRATEGIES } from "../../lib/constants";
import type { Exchange, Instrument, TickerSuggestion } from "../../lib/types";
import { currencyForSymbol, emptyInstrument, money, today } from "../../lib/workspace-utils";
function updateRow(setRows: React.Dispatch<React.SetStateAction<Instrument[]>>, index:number, patch:Partial<Instrument>){ setRows(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row)); }
function TickerInput({value,markets,onChange}:{value:string;markets:Exchange[];onChange:(v:string)=>void}){ const [results,setResults]=useState<TickerSuggestion[]>([]); useEffect(()=>{const q=value.trim();if(!q){setResults([]);return;} const t=setTimeout(()=>searchTickers(q,markets).then(r=>setResults(r.results)).catch(()=>setResults([])),260);return()=>clearTimeout(t)},[value,markets]); return <div className="ticker-input-wrap"><input value={value} placeholder="Ticker or company" onChange={e=>onChange(e.target.value)}/>{value.trim()&&results.length>0&&<div className="ticker-suggestions">{results.slice(0,6).map(r=><button key={`${r.symbol}-${r.market}`} type="button" onMouseDown={e=>{e.preventDefault();onChange(r.symbol);setResults([])}}><strong>{r.symbol}</strong><span>{r.name||r.label}</span><em>{r.market} · {r.currency}</em></button>)}</div>}</div> }
export function InstrumentEditor({rows,setRows,trading,markets}:{rows:Instrument[];setRows:React.Dispatch<React.SetStateAction<Instrument[]>>;trading:boolean;markets:Exchange[]}){ return <div className="editor-grid">{rows.map((item,index)=><article className="instrument-row" key={index}><TickerInput value={item.symbol} markets={markets} onChange={symbol=>updateRow(setRows,index,{symbol})}/>{trading&&<input type="date" value={item.purchase_date||today()} onChange={e=>updateRow(setRows,index,{purchase_date:e.target.value})}/>} {trading&&<input type="number" min="0" step="0.01" value={item.average_cost||""} placeholder="Avg price" onChange={e=>{const average_cost=Number(e.target.value);updateRow(setRows,index,{average_cost,book_cost:average_cost*(item.shares||0)})}}/>}{trading&&<input type="number" min="0" step="1" value={item.shares||""} placeholder="Shares" onChange={e=>{const shares=Number(e.target.value);updateRow(setRows,index,{shares,book_cost:(item.average_cost||0)*shares})}}/>}{trading&&<div className="computed-cost"><span>Book cost</span><strong>{money((item.average_cost||0)*(item.shares||0),currencyForSymbol(item.symbol))}</strong></div>}{!trading&&<input value={item.watch_reason||""} placeholder="Reason for watchlist" onChange={e=>updateRow(setRows,index,{watch_reason:e.target.value})}/>}<select value={item.intent||"Hold / Watch"} onChange={e=>updateRow(setRows,index,{intent:e.target.value})}>{INTENTS.map(x=><option key={x}>{x}</option>)}</select><select value={item.strategy||"Buy-dip"} onChange={e=>updateRow(setRows,index,{strategy:e.target.value})}>{STRATEGIES.map(x=><option key={x}>{x}</option>)}</select><span className="symbol-remove" role="button" onClick={()=>setRows(current=>{const next=current.filter((_,i)=>i!==index);return next.length?next:[emptyInstrument(trading?"Trading":"Watching")]})}>X</span></article>)}</div> }
